version: '3.8'

services:
  # Nome do serviço no Docker. Usaremos 'db'
  db:
    image: postgres:16-alpine # Imagem oficial do PostgreSQL leve
    restart: always
    environment:
      # Variáveis de ambiente padrão do PostgreSQL
      POSTGRES_USER: your_db_user      # <-- MUDAR! Usuário do banco de dados
      POSTGRES_PASSWORD: your_db_password # <-- MUDAR! Senha do banco de dados
      POSTGRES_DB: agendamento_db       # Nome do banco de dados

    ports:
      # Mapeia a porta 5432 do container para a porta 5432 da sua máquina
      - "5432:5432"

    volumes:
      # Persiste os dados em um volume nomeado para que os dados não se percam quando o container for parado
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: